### ISSUE TITLE
Cookie保留的问题

### ISSUE THREAD

**Issue by zohead** [binux/qiandao#10]
新建签到模板，如果有多个请求，第一个登录请求完成之后生成的Cookie
在后面的请求中是否会直接使用？还是需要自己通过变量提取方式提取出Cookie值？

现在在Web签到测试中输入用户名和密码测试提示签到失败，
但结果中只能看到哪一步出错，没有详细的request和response信息，不太方便调试的。

谢谢

**Comment by binux** [comment]
用单步调试啊

**Comment by zohead** [comment]
在 qiandao.today 网站上（https://qiandao.today/tpl/xxx/edit）编辑模板请求，这个如何单步调试？
如果只对单个请求单独输入用户名和密码单步测试，这样没有cookie也完成不了

**Comment by binux** [comment]
点开请求详情，切换到测试面板，输入用户名密码，点测试。
对每个请求重复这个步骤。请求中的 cookie 能在测试面板中看到，并会被带入下一个请求中。
