### ISSUE TITLE
v2ex-cookie版在qiandao.today正常，在自己vps上却不能运行

### ISSUE THREAD

**Issue by Hzbeta** [binux/qiandao#108]
执行日志显示：

failed at 2/5 request, , https://www.v2ex.com/mission/daily

在模板测试时，发现第二条请求返回302，而在qiandao.today上就是正常的返回200

我的vps是美国ip,centos7，安装的时候yum好像没有python-pbkdf2包，就没装它，不知道是不是和这个有关。

在qiandao.today上测试第二条请求时，填入cookie后，cookies分类下面出现A2 PB3_SESSION 2EX_LANG V2EX_TAB _ga五个字段，但是在自己的vps上就只有PB3_SESSION V2EX_LANG V2EX_TAB三个。是不是提交cookie的时候出了问题呢？

**Comment by MoeGakuen** [comment]
你怎么就不考虑封IP呢

**Comment by Hzbeta** [comment]
昨天试的时候返回的也是200，但是还是显示失败，而且我用这台VPS做代理，是可以用浏览器正常登录签到的

**Comment by haodong** [comment]
测试同。

**Comment by foxni** [comment]
跟楼主情况一样，关键是很尴尬的，现在回qiandao.today上测试也出现了302

**Comment by goxofy** [comment]
我也是一样的情况，很奇怪

**Comment by binux** [comment]
因为qiandao.today 上配置了很多代理
