### ISSUE TITLE
post如何自动获取当前日期？

### ISSUE THREAD

**Issue by sexchen** [binux/qiandao#113]
![qiandao](https://user-images.githubusercontent.com/17498101/47548120-894a4580-d92a-11e8-99dd-a522bffed79c.png)

网站的签到，post中必须填写签到日期，也必须为当日，不知道应该用怎么操作，这个可以实现吗，应该用什么函数？

**Comment by binux** [comment]
{{ date_time() }}

**Comment by sexchen** [comment]
> {{ 约会时间（） }}

大佬，这个函数是有用的，但是好像不能解决我的问题，他提交的参数是：
m=2018-10-26%2004%3A53%3A29    
但是我需要的是年月日分开明确的提交，百度查了一下，发现好多语言都用的是date_time   没查出来该怎么只获取单独的年月日，大佬百忙之中能不能在抽空回复一下我。

**Comment by binux** [comment]
`{{ date_time().split('-')[0] }}`

**Comment by sexchen** [comment]
> `{{ date_time().split('-')[0] }}`

感谢大佬的回复，确实问题解决了一半了，我使用{{ date_time().split('-')[0] }}   {{ date_time().split('-')[1] }}  成功获取到‘年’和‘月’  但是‘日’并不能获取到   
如果使用{{ date_time().split('-')[2] }}  获取的是
26%2004%3A53%3A29
后面带有一串乱码
我试着使用{{ date_time().split('%')[0] }}   出现的是完整的时间
2018-10-26%2004%3A53%3A29
如果{{ date_time().split('%')[1] }}    则为空白

百度了一下特殊符号需要加\\ 
{{ date_time().split('\\%')[0] }}

但是好像也没有效果   分割不了

我在想是不是符号错了   其实‘%’ 是空格
{{ date_time().split(' ')[0] }}
依然无效

没办法了  ，大佬再教教我可以 吗

**Comment by binux** [comment]
`{{ date_time().split(' ')[0].split('-')[-1] }}`

**Comment by sexchen** [comment]
![image](https://user-images.githubusercontent.com/17498101/47694002-d97d1c80-dc36-11e8-9a2b-048548cb179a.png)
![image](https://user-images.githubusercontent.com/17498101/47694010-e437b180-dc36-11e8-8e13-5b425697c30b.png)

完美的解决了我的问题emmmmmmm
我要哭了哇！！！！！！！！
为什么时间是29号啊！！！！今天已经三十了啊！！！！
前两天还是准的啊！！！！！
我哭给你看！！！！！！！
呜呜呜呜呜呜呜！！！！！

**Comment by binux** [comment]
{{ date_time(time_difference=8) }} 看看

**Comment by sexchen** [comment]
> {{ date_time(time_difference=8) }} 看看

测试时直接就
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

**Comment by binux** [comment]
现在应该好了，你也不用加 time_difference 了

**Comment by sexchen** [comment]
> 现在应该好了，你也不用加 time_difference 了
o了  谢谢大佬

**Comment by sexchen** [comment]
大佬  出大湿啦！
![image](https://user-images.githubusercontent.com/17498101/48203471-8cb9e400-e3a2-11e8-9aba-9271e1cc6cad.png)

这可如何是好   一直登陆不上  ，重新抓包上传也是这样  但是只签到的话（手打cookie）没问题

**Comment by sexchen** [comment]
今天又正常了.....  大佬无视上面的问题把
