### ISSUE TITLE
网站挂了，如何获取模板呢？

### ISSUE THREAD

**Issue by hyyzhuceyong** [binux/qiandao#115]
额。之前就用的你的网站签到的，现在想自己用VPS弄个，但是你的网站挂了。模板如何下载呢？

**Comment by hyyzhuceyong** [comment]
哦。原来是被墙了。。。有备用的网站不dalao！！

**Comment by binux** [comment]
https://qiandao.binux.me

**Comment by hyyzhuceyong** [comment]
> https://qiandao.binux.me
> […](#)

收到。谢谢。
