### ISSUE TITLE
建议增加签到失败邮件提醒

### ISSUE THREAD

**Issue by iBreaker** [binux/qiandao#129]
每次签到任务失败都不知道，过了十几天后才发现一直没有签到成功。希望增加邮件消息订阅，可以及时通知到用户

**Comment by binux** [comment]
一直以来就有这个功能

**Comment by iBreaker** [comment]
请问需要自己配置吗，是在哪里配置？要是默认就有的话好像没有收到过提醒的邮件

**Comment by binux** [comment]
你是自己搭建还是使用别人的？用谁的？
你点了验证邮箱吗？qq邮箱收不到

**Comment by iBreaker** [comment]
qq邮箱手不到哦  好的  多谢

**Comment by zlhdd108** [comment]
你好，问一下，我是自己用docker搭建的，smtp用的是网易的邮箱，注册邮箱用的腾讯的qq邮箱，是不是只要收件箱是qq邮箱，即便自己配置smtp也收不到呢？
