### ISSUE TITLE
变量提取能否支持 header

### ISSUE THREAD

**Issue by woosley** [binux/qiandao#13]
瞅了一眼代码，getdata本身支持从 content, header 和status提取数据，但是在测试页面变量提取只支持 content，能否加入从 header 中提取变量的功能。

**Comment by binux** [comment]
界面上没有留接口，需要两个选单，一个选 from 一个选 header 字段名，太麻烦了
如果你需要的是 CSRF 的话，页面内容里面肯定会有对应的值能被提取到的

**Comment by woosley** [comment]
谢谢，检查了一下http请求，的确是这样的
