### ISSUE TITLE
提一些建议，不知作者是否还维护此项目

### ISSUE THREAD

**Issue by g1thub-h** [binux/qiandao#145]
以下建议全部是针对docker或者是自己搭建的网站来提出的。避免给作者的服务器增加压力

1.如果可以的话希望能从python2升级到python3
2.希望加入定时功能，以发布模板的当前时间的24h这个过于模糊，希望能自定义时间
3.希望加入发信设置 例如：server酱的提醒功能 能通知哪些任务成功或者失败

请求作者能在空闲时间维护一下项目

**Comment by AragonSnow** [comment]
不是作者，作为使用者做了一些修改：
1,py环境需要修改较多，暂时没做的打算
2，3，功能已实现，请参考这个：
https://github.com/AragonSnow/qiandao
docker镜像：
https://hub.docker.com/r/asdaragon/qiandao

**Comment by g1thub-h** [comment]
> 
> 
> 不是作者，作为使用者做了一些修改：
> 1,py环境需要修改较多，暂时没做的打算
> 2，3，功能已实现，请参考这个：
> https://github.com/AragonSnow/qiandao
> docker镜像：
> https://hub.docker.com/r/asdaragon/qiandao

感谢
