### ISSUE TITLE
手动新增模板，上传HAR后，测试提示网络连接失败 net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by caixlcq** [binux/qiandao#159]
手动新增模板，上传HAR后，测试提示网络连接失败 ， net::ERR_CONNECTION_REFUSED
尝试了把公共模板下载下来，再上传，一样的提示网络连接失败  

测试版本：20211204
搭建方案：Docker

**Comment by xuanhuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
