### ISSUE TITLE
关于编辑器的使用与cookies变量

### ISSUE THREAD

**Issue by eromoe** [binux/qiandao#19]
刚刚在玩这个，感觉挺有意思的~
目前发现一些问题，所以来说说
1. 比如我有5个url， 如果我要调第二个url 要点开第一个点下测试，然后再点开第二个点测试，而且测试界面的那几个选项卡很容易让人迷糊=。=，我试了好几次才有点搞懂大概什么意思。cookies貌似是后一个请求覆盖前一个，重新测试第一个请求的话也是用这个cookies，类似requests 的session吧，这个步骤可能要详细写一下，要不可能会让刚接触的人搞不懂。。。
2. 那个url列表，双击经常没反应。。。有时要多点几下才行。。。不知道算不算bug
3.正则提取变量自动拿第一个group ，这个在doc里说明一下比较好吧
4.关于获取到的cookies，如何能转成变量，我有碰到一个登陆的情况：请求url_A拿到的cookies中的sid，签到url_B需要把这个sid填在querystring上，这个不知道怎么设变量。

如果能做个详细的编辑器使用用例就更好啦=。=~

**Comment by ixiusama** [comment]
呃，能否解释一下第一点要如何进行设定 我也遇到这个问题看了一下 #20 并没有看得懂，想仔细询问一下
