### ISSUE TITLE
已经yum install tornado 仍然提示ImportError: No module named tornado.ioloop

### ISSUE THREAD

**Issue by evindu** [binux/qiandao#22]
./qiandao.py xiami.har [--key=省略cookie; ] [env.json]

Traceback (most recent call last):

  File "./qiandao.py", line 12, in <module>

   from tornado.ioloop import IOLoop

ImportError: No module named tornado.ioloop

-bash: ]: 未找到命令

**Comment by binux** [comment]
`pip install tornado`

**Comment by evindu** [comment]
@binux  我已经 用过pip install tornado 了 而且 也upgrade了 还是提示没有

**Comment by binux** [comment]
你装 tornado 用的 pip 和你运行的 python 是同一个吗？
