### ISSUE TITLE
关于本地lite版,区别以及部署方法

### ISSUE THREAD

**Issue by 264768502** [binux/qiandao#24]
请问本地lite版和服务器版有什么区别?
如何部署本地lite版,因为想在Windows上直接部署,然后又不想用数据库.
在博客上有看到说有个lite版,但是github上又没看到相关说明.
麻烦了.

**Comment by binux** [comment]
lite 版指的是 https://github.com/binux/qiandao#qiandaopy，没有 web 前端，命令行执行
