### ISSUE TITLE
Ip封锁问题

### ISSUE THREAD

**Issue by 1kevin335200** [binux/qiandao#25]
类似chiphell论坛，会封锁部分vps的ip段，比如qiandao.today用的ip.
这种情况是不是无解了。。

**Comment by binux** [comment]
架个代理

**Comment by 1kevin335200** [comment]
请教如何建立代理？我是有国内的及一些没有被封的vps的代理，不过是ss..
我曾试过在openshift上nginx+ss尝试反代chiphell，但没成功。
因为我知道虾米也封国外ip,查看了虾米的签到模板，看到虾米的签到有请求到pyproxy.coding.io，不过今天404了，不是很清楚原理。。

**Comment by binux** [comment]
pyproxy.coding.io 运行的是 https://github.com/binux/pyproxy ，访问不了应该是被 coding 干掉了吧

**Comment by 1kevin335200** [comment]
恩，我尝试一下使用您的pyproxy来实现代理
