### ISSUE TITLE
如果body是json的话，就不能签到了

### ISSUE THREAD

**Issue by RitzoneX** [binux/qiandao#26]
现在是把json用表单发送出去了

**Comment by binux** [comment]
你怎么知道它用表单发出去的？

**Comment by RitzoneX** [comment]
因为服务器返回load json error

**Comment by binux** [comment]
你格式错了呢

**Comment by RitzoneX** [comment]
没有，用postman可以发送出去

**Comment by binux** [comment]
我意思是，没有双引号，缺逗号等。
你怎么知道就是用表单发送出去了？

**Comment by RitzoneX** [comment]
给个网址你
https://news.futunn.com/market/9185
当中post  client_report里request payload是json
但是用签到模拟就出错了

**Comment by binux** [comment]
你说的什么意思？你能发一个发布请求我看看吗？

**Comment by RitzoneX** [comment]
注意Request Payload那里
<img width="438" alt="2016-06-13 15 40 16" src="https://cloud.githubusercontent.com/assets/7511260/16000271/ee7db326-317d-11e6-9b86-d3ee8af34f50.png">

测试结果
<img width="584" alt="2016-06-13 15 40 34" src="https://cloud.githubusercontent.com/assets/7511260/16000276/f84b0b10-317d-11e6-963b-bddd299bb729.png">

har:
[news.futunn.com.har.zip](https://github.com/binux/qiandao/files/311402/news.futunn.com.har.zip)

**Comment by binux** [comment]
fixed via 4ddde18ed0362941c74940bcfa98d30259c2380c
