### ISSUE TITLE
百度贴吧签到的几个问题

### ISSUE THREAD

**Issue by wujunze** [binux/qiandao#27]
1. name_of_bar这个选项   是贴吧名字?
2. 能不能设置所有帖吧都签到?

**Comment by binux** [comment]
1. 是
2. 不能

**Comment by wujunze** [comment]
楼主能不能考虑加上所有贴吧签到的功能呢?    
可以参考一下  无名智者的贴吧签到程序

**Comment by binux** [comment]
Qiandao 是个框架，给它加循环太麻烦了。
不考虑
