### ISSUE TITLE
本人小白 能不能下个vps搭建的说明

### ISSUE THREAD

**Issue by xau0at** [binux/qiandao#28]

**Comment by xzc0001** [comment]
可以vps搭建，自己研究一下，不难的。http://sign.hura.ga

**Comment by zjking** [comment]
为什么我把账户role设置为admin，但是还是没办法审批发布的模板呢

**Comment by getoutboy** [comment]
我也是小白，请问如何搭建，谢谢~

**Comment by xau0at** [comment]
参考这篇文章 已经成了 https://xkblog.xyz/qiandao-today-Setup.html
