### ISSUE TITLE
请问要如何结合nginx使用呢

### ISSUE THREAD

**Issue by xiaofami** [binux/qiandao#37]
自己的VPS上有LNMP环境和AMH管理面板，于是想通过在AMH中创建虚拟主机，文件上传网站根目录的方式部署，顺便配置域名，类似于安装wordpress。不过发现这个签到框架是用tornado的。。。参考了[Running and deploying](http://www.tornadoweb.org/en/stable/guide/running.html)、[Starting Tornado App on a domain name ( without the port number )](http://serverfault.com/questions/246623/starting-tornado-app-on-a-domain-name-without-the-port-number)和[部署项目Nginx+Tornado+Supervisor](http://www.jianshu.com/p/9bebb99368ea)，大致是说用nginx监听80端口作为反向代理，不过具体配置没成功，对应域名的nginx配置文件大致上是参照serverfault上那篇修改的。

**Comment by binux** [comment]
```
upstream p8200 {
    server 127.0.0.1:8200;
}

server {
    listen         80;
    listen         [::]:80;
    server_name    qiandao.today;

    location / {
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass http://p8200;
    }
}
```

**Comment by xiaofami** [comment]
谢谢，修改配置后可以通过域名直接访问了。不过css和js无法加载，为css和js尝试指定web目录为root path也没有效果。另外同一主机的其他域名通过8200端口也可以访问到。

**Comment by binux** [comment]
css 和 js 也反代啊

**Comment by getoutboy** [comment]
作者能否发一个简单的本地建服务教程，谢谢！！！！
