### ISSUE TITLE
timestamp 不工作

### ISSUE THREAD

**Issue by legendtang** [binux/qiandao#40]
{{ timestamp() }} 得到的结果是 u'timestamp': u''，我猜想是在填写信息的时候接受了 timestamp 的空字符串而没有调用 timestamp() 这个 function，错误如 https://github.com/binux/qiandao/issues/39#issuecomment-268002746 所示

**Comment by binux** [comment]
fixed in https://github.com/binux/qiandao/commit/9398e69f2b52bbe5701969917a6dbddb5f208579

**Comment by legendtang** [comment]
@binux 似乎更新后问题依然没有变化

**Comment by legendtang** [comment]
@binux 另一个问题，`timestamp()` 在 jinja 里似乎没有办法进行数学运算，因为 Python 的 timestamp 是以秒为单位，业界一般使用 JS 的 `new Date().getTime()` 的以毫秒为单位的 timestamp 作为参数传递，有无解决方法？

**Comment by binux** [comment]
{{ "%d" | format(timestamp() * 1000) }}

**Comment by legendtang** [comment]
@binux 感谢！
