### ISSUE TITLE
怎么安装.py文件呢？

### ISSUE THREAD

**Issue by Mathisdifficult** [binux/qiandao#42]
AMH管理面板，在AMH中创建虚拟主机，文件上传网站根目录的方式部署，配置域名，类似于安装wordpres的方法 但是不行

**Comment by MoeGakuen** [comment]
你也是厉害，py是脚本文件不能用php之类的运行。面板没用，直接linux命令执行

**Comment by Mathisdifficult** [comment]
python版本有要求吗？我的是2.6.6要不要升级到2.7以上？

**Comment by kslr** [comment]
没有要求就不需要

**Comment by kslr** [comment]
能close掉吗

**Comment by Mathisdifficult** [comment]
好的，谢谢你

**Comment by kslr** [comment]
点击尾部的Close按钮就可以了
