### ISSUE TITLE
如何才能用mysql数据库呢？

### ISSUE THREAD

**Issue by xuexiaokang** [binux/qiandao#46]
我已经将config.py中的
class mysql(object):
    host = mysql_url.hostname or 'localhost'
    port = mysql_url.port or '3306'
    database = mysql_url.path[1:] or 'qiandao'
    user = mysql_url.username or 'qiandao'
    passwd = mysql_url.password or None
改为自己的数据库信息
class mysql(object):
    host = mysql_url.hostname or 'localhost'
    port = mysql_url.port or '3306'
    database = mysql_url.path[1:] or 'qiandao'
    user = mysql_url.username or 'qiandao'
    passwd = mysql_url.password or '123456789'
但是发现运行run.py之后还是没用mysql数据库。
是不是还有哪里要修改？

**Comment by binux** [comment]
db_type
