### ISSUE TITLE
为什么已经设置了mysql并运行成功，但是每次运行都提示连接sqlite3端口失败呢？

### ISSUE THREAD

**Issue by kukudemajia** [binux/qiandao#47]
这个bug怎么修复呢？
![qq 20170214113533](https://cloud.githubusercontent.com/assets/17118600/22914129/e333b496-f2a9-11e6-807b-72fb5c4f5f58.jpg)
config.py

class mysql(object):
    host = 'localhost'
    port = '3306'
    database = 'qiandao'
    user = 'qiandao'
    passwd = 'test'  

class sqlite3(object):
    path = './database.db'

db_type = os.getenv('mysql')

class redis(object):
    host = redis_url.hostname or 'localhost'
    port = redis_url.port or 6379
    passwd = redis_url.password or None
    db = int(os.getenv('REDIS_DB_INDEX', 1))
evil = 100

**Comment by binux** [comment]
`db_type = 'mysql'`

**Comment by kukudemajia** [comment]
这个改过来了，结果还是一样，实在不清楚为什么？把config.pyc删除重启后运行还是一样的结果

**Comment by binux** [comment]
你说的是第一行这个 `Error 61 connecting to localhost:6379. Connection refused.` 吗？这是连接 redis 的，没有也没关系。
