### ISSUE TITLE
自建的qiandao无法使用mailgun发送邮件

### ISSUE THREAD

**Issue by Mathisdifficult** [binux/qiandao#49]
config.py中的mailgunkey已经设置
mailgun中域名已经验证
问题1.服务器除了config.py是否还需设置哪里？
问题2.mailgun除了验证域名是否还需如何操作？

**Comment by binux** [comment]
解释一下「无法使用mailgun发送邮件」是什么意思。

**Comment by Mathisdifficult** [comment]
就是重置密码收不到邮件（包括注册帐号的验证邮件），签到失败的邮件等

**Comment by binux** [comment]
mailgun 有发送记录吗？

**Comment by Mathisdifficult** [comment]
没有发送纪录。

**Comment by binux** [comment]
那你去 https://github.com/binux/qiandao/blob/bcbc4da3405db6b5da5f585f6c5d6c589956b32e/libs/utils.py#L135 print 一下 config.mailgun_key 看有没有设置上 mailgun_key

**Comment by Mathisdifficult** [comment]
谢谢你问题解决了，qiandao/libs/utils.py下面url="https://api.mailgun.net/v2/mail.qiandao.today/messages"中
mail.qiandao.today改成自己的域名就ok了
