### ISSUE TITLE
无法url设置为有变量的

### ISSUE THREAD

**Issue by duhai973** [binux/qiandao#51]
将url里加入变量保存后无法使用，会自动urlencode，希望可以改进支持url里有变量的形式

**Comment by binux** [comment]
![image](https://cloud.githubusercontent.com/assets/646451/23253689/5c8a5778-f9ad-11e6-9573-18487fb56086.png)

你是说这样吗？

**Comment by duhai973** [comment]
有时候它会自动urlencode转码一下

**Comment by duhai973** [comment]
好像是可以的，不过测试的时候会有点问题，上图
![image](https://cloud.githubusercontent.com/assets/20506880/23259203/f342bbde-fa06-11e6-9f71-6e81896c4f7a.png)
点击然后会变成
![image](https://cloud.githubusercontent.com/assets/20506880/23259238/1873d2c6-fa07-11e6-9f1e-cd6858852dbd.png)
@binux

**Comment by duhai973** [comment]
问题不大
