### ISSUE TITLE
密码重置采用的邮件发送功能能否改为别的服务，比如SMTP

### ISSUE THREAD

**Issue by xuexiaokang** [binux/qiandao#52]
mailgun服务总是不好用，还要绑定信用卡，密码重置采用的邮件发送功能能否改为别的服务，比如SMTP

**Comment by MoeGakuen** [comment]
谁说要绑定信用卡。。。

**Comment by xuexiaokang** [comment]
@MoeGakuen 应该是针对现在新的用户的，现在新注册的都要验证了才能正常对外发送邮件

**Comment by xuexiaokang** [comment]
没有绑定信用卡的用户只能发给Authorized Recipients中已验证的邮箱地址，可能是官网开始防垃圾邮件了，所以要信用卡了

**Comment by xuexiaokang** [comment]
@MoeGakuen 现在的免费账户会提示：Free accounts are for test purposes only. Please upgrade or add the address to authorized recipients in Account Settings.

**Comment by binux** [comment]
你重写 https://github.com/binux/qiandao/blob/master/libs/utils.py#L134 不就好了

**Comment by xuexiaokang** [comment]
@binux 就是写不来，大神写一个吧

**Comment by binux** [comment]
SMTP 速度到达率等等都不如 SAAS。。又没什么用。。

**Comment by MoeGakuen** [comment]
@xuexiaokang 我是老用户，不知道

**Comment by xuexiaokang** [comment]
mailgun是好，可惜现在不给新用户免费用了，要不然用这个还是不错的

**Comment by xuexiaokang** [comment]
@MoeGakuen 羡慕老用户

**Comment by MoeGakuen** [comment]
mailgun 什么都好，就是腾讯那恶心，还有就是发国内邮箱延迟

**Comment by binux** [comment]
感谢 @c1ay  的 PR https://github.com/binux/qiandao/pull/55
