### ISSUE TITLE
请问 ./qiandao.py tpl.har [--key=value]* [env.json]  这条命令如何正确使用

### ISSUE THREAD

**Issue by Anyfc** [binux/qiandao#54]
比如说已经从qiandao.today 下载  什么值得买.har  模板，账号密码在哪里设置？env.json 从哪里获取

**Comment by binux** [comment]
在 qiandao.today 看它要求什么变量，用户名密码的话就 

./qiandao.py 什么值得买.har --username=你的用户名 --password=你的密码

**Comment by Anyfc** [comment]
@binux 如果是cookie的话，是不是把cookie粘贴进env.json，
然后 ./qiandao.py 什么值得买.har --cookie=env.json   就可以了？

**Comment by binux** [comment]
你需要粘贴成 json 的 cookie 字段上

**Comment by Anyfc** [comment]
@binux 哦，不能直接使用 cookies获取助手 扩展 获取到的cookies

**Comment by binux** [comment]
可以啊，但是最后的 env.json 需要是一个 JSON 格式的文件，例如
```
{
  "cookies": "xxxxxxxxxxxxxxxxxxxxx"
}
```

**Comment by Anyfc** [comment]
@binux 明白了，多谢
