### ISSUE TITLE
使用qiandao.py直接签到不成功

### ISSUE THREAD

**Issue by koolca** [binux/qiandao#64]
命令如下：python qiandao/qiandao.py har/jdjr.har har/jdjr.json
qiandao failed! failed at 1/1 request, , http://vip.jr.jd.com/newSign/doSign
搭建Docker通过web可以签到成功。可以确定的是json文件中cookie是一样的。
同样的，还有一些网站的签到通过命令调用qiandao.py签到显示qiandao success，但实际没有成功。

**Comment by binux** [comment]
模板需要添加断言才能支持成功检查。
