### ISSUE TITLE
有关签到模板时间参数的疑问

### ISSUE THREAD

**Issue by yingziwu** [binux/qiandao#65]
1. 使用`{{ timestamp() }}`参数（例如： `1493621542.44`），获得的时间戳含有两位小数，并不是毫秒级时间戳，如何获得形如`1493620949139`的时间戳（Python：`int(time.time()*1000)`）。

1. 如何获取当前月份、年份？

**Comment by binux** [comment]
1.`{{ timestamp() * 1000 | int }}`
2. 不可以

**Comment by yingziwu** [comment]
好吧。
看了`libs/utils.py`文件，好像只支持`md5`、`quote_chinese`、`quote_chinese`、`utf8`、`timestamp`几个函数，作者不考虑多支持几个吗？

**Comment by binux** [comment]
有需要可以添加
