### ISSUE TITLE
提取上一次请求的参数这一节不明白

### ISSUE THREAD

**Issue by run27017** [binux/qiandao#67]
在howto的**编辑器使用**那一栏里，第三点的操作不明白：

> 请求中需要上一个请求中的某些数据时，使用变量提取，通过正则提取数据保存在环境变量中。使用 ab(\w+)cd，组选择器，选择其中的一部分。

能不能给出个具体的操作描述

**Comment by binux** [comment]
https://qiandao.today/tpl/8/edit `{{ once }}`

**Comment by run27017** [comment]
通过示例，明白了。不过有可能的话还是希望充分补充一下文档。
