### ISSUE TITLE
HTTPS网站POST方式返回数据中的值无法匹配

### ISSUE THREAD

**Issue by pk000** [binux/qiandao#72]
用Chrome记录的har文件中，有HTTPS网站签到使用POST方法后，返回的content内容如下：
  "content": {
    "size": 56,
    "mimeType": "text/html",
    "text": "{\"msg\":\"\\u83b7\\u5f97\\u4e86 164 MB\\u6d41\\u91cf.\",\"ret\":1}"
  },
msg里面的内容是“获得了 164 MB流量.”。
但是测试的时候返回的数据显示是乱码，无法匹配。

**Comment by binux** [comment]
这是 JSON 的编码，你匹配 `"\u83b7\u5f97\u4e86 164 MB\u6d41\u91cf."`不就完了。

**Comment by pk000** [comment]
这样匹配不成功。

**Comment by binux** [comment]
那就填4个

**Comment by pk000** [comment]
4个也不行

**Comment by pk000** [comment]
原始返回：
`  "content": {
    "size": 75,
    "mimeType": "text/html",
    "text": "{\"msg\":\"\\u60a8\\u4f3c\\u4e4e\\u5df2\\u7ecf\\u7eed\\u547d\\u8fc7\\u4e86...\",\"ret\":1}"
  },`

对应文本：
`您似乎已经续命过了...`

网页上测试返回的结果：
`�P ��R���T���2���dQI�������a�>\ω˶jɱKvv�:c��V�4�����Pp����`

**Comment by binux** [comment]
你是不是勾选了 gzip 或者类似的东西？

**Comment by pk000** [comment]
啊！这个才是关键！取消gzip就可以看到原始文本了！
谢谢解答！

**Comment by pk000** [comment]
还有一个问题。
最后签到提取变量`__log__`的时候用正则表达式能够匹配到`\u60a8\u4f3c\u4e4e\u5df2\u7ecf\u7eed\u547d\u8fc7\u4e86...`，但是不能转换为需要的中文字符。

**Comment by binux** [comment]
不能
现在失败应该会显示因为什么规则失败啊

**Comment by pk000** [comment]
哦，明白了。
还以为失败日志可以不显示哪条规则失败，直接显示提取的文本呢。
