### ISSUE TITLE
[建议]将所有环境相关的变量抽取到env_example.json

### ISSUE THREAD

**Issue by tinpont** [binux/qiandao#73]
当前修改配置我想大部分人都是直接修改config.py的，我建议将可配置的环境变量都写在env_exapmle.json，放到项目根目录，然后 .gitignore 添加 env.json 的忽略。

这样用户就清楚知道有什么选项是可配置的，并且可以简单复制env_example.json到env.json进行环境变量配置。执行./run.py的时候默认加载同目录env.json方便用户。

另一个好处就是用户修改的变量不会影响到从git更新代码。

有部分配置我个人觉得需要抽出来的，比如说：

> bind 部分人通过配置nginx使用80端口访问，希望只绑定本地IP
> domain 同上
> mail相关
> 等

**Comment by tinpont** [comment]
同时我也看到一些issue提及到dev.json的疑惑（包括我），一开始使用并没有看到dev.json的介绍，需要看到源码之后才清楚原来是json文件存放环境变量。

**Comment by binux** [comment]
你可以新建一个 local_config.py 然后拷贝修改你需要的配置文件进去啊。

**Comment by tinpont** [comment]
是的，我可以新建，也可以直接修改config.py，但是要么我需要改.gitignore，要么我让这个local_config.py在git中一直显示为待提交文件。无论哪种都会导致后续直接从你项目git pull下来造成可能的冲突。Thanks.

**Comment by binux** [comment]
Untracked files 不会影响 Pull
