### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by xi452686571** [binux/qiandao#79]
failed at 1/4 request, error:SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'), https://www.v2ex.com/signin

I cloned the code to my ubuntu 16.04 LTS, and downloaded the template from https://qiandao.today/tpls/public.

**Comment by binux** [comment]
https://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

**Comment by xi452686571** [comment]
Thanks, but the problem is not on this.
I opened the Koolproxy with global https on Router.
After I disabled the koolproxy, it worked.

**Comment by xi452686571** [comment]
Now I close the issue.
