### ISSUE TITLE
关于百度登陆

### ISSUE THREAD

**Issue by lyjamare** [binux/qiandao#8]
现在的百度登陆，百度进行了rsa密码传输加密
我先做的是百度贴吧签到，其实只是用到了bduss这个cookie中的参数，就可以模拟签到了

不过我想是真正登陆百度，然后获取到cookie，所以希望楼主可以看看百度的密码加密是如何做的？

**Comment by binux** [comment]
有很多带登录的开源贴吧签到程序，看看怎么实现的就好了
