### ISSUE TITLE
为什么签到经常会推后2个小时

### ISSUE THREAD

**Issue by xugui0821** [binux/qiandao#87]
模板设定的是每天签到，上次签到成功是1小时前，也就是0点过几分，下次签到时间为什么会是明天2:05分？经常会这样，0点过几分点执，没几天又往后推了2小时，白天的签到好像不会这样。
![image](https://user-images.githubusercontent.com/21220256/36040360-2bda24ce-0e00-11e8-8b38-0f2e539061d5.png)

**Comment by xugui0821** [comment]
怎么取消这个限制？很多网站每天前几个签到的积分都是多些的，你说的这个指不定前一天还是后一天应该没什么问题吧，就算时间不同步不还是24小时签一次吗，不会出现一天签2次然后漏签吧。

**Comment by binux** [comment]
取消不了。签到是有一个队列的，每天签到时间是不固定的，时间长了之后会积累差额，导致跨天。

**Comment by xugui0821** [comment]
好吧谢谢了

**Comment by xugui0821** [comment]
找到了，删掉worker.py 106 107行就行了..
