### ISSUE TITLE
激活邮件中的链接没有端口号，导致链接失效

### ISSUE THREAD

**Issue by gyf9835** [binux/qiandao#89]
默认端口时，激活邮件中的链接没有端口号，导致链接失效
![01](https://user-images.githubusercontent.com/24644280/37079810-dc1bbd66-221e-11e8-97ce-477ac8bc5e42.png)

![02](https://user-images.githubusercontent.com/24644280/37079814-de949fb8-221e-11e8-8caf-ada618618060.png)

*****

![03](https://user-images.githubusercontent.com/24644280/37079815-e037d2ae-221e-11e8-8183-40c55b5286b0.png)

**Comment by MoeGakuen** [comment]
反代一下就是

**Comment by ixmu** [comment]
使用nginx进行一下反代即可去除端口号访问
