### ISSUE TITLE
cookie的签到都失败了

### ISSUE THREAD

**Issue by hillwah** [binux/qiandao#9]
![image](https://cloud.githubusercontent.com/assets/2394352/7176834/7b869ef4-e454-11e4-98ae-2afc64dbc1aa.png)
自己本地搭建的qiandao，用账号登陆的模板几乎都可以成功。但是cookie版的三个都出错了。
这个错误可能不够详细，但我不知道哪里可以看到更详细的信息。

**Comment by hillwah** [comment]
确认一个问题，并不是所有的cookie签到都失效。只有smzdm的有问题，模板用的是qiandao.today的。

**Comment by binux** [comment]
smzdm 加了一个浏览器检测，模板不好写

**Comment by hillwah** [comment]
是User-Agent吗？

**Comment by binux** [comment]
不是
