### ISSUE TITLE
HTTP 599: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by oe77** [binux/qiandao#92]
(1)当我使用mailgun方式进行发邮箱时,会提示no module named pycurl!
![20180322140759](https://user-images.githubusercontent.com/12007315/37754093-0d47f5f4-2ddb-11e8-8d6a-7457e197b7a5.png)

(2)pip install pycurl (7.43.0.1)再运行时,会提示HTTP 599: SSL certificate problem: unable to get local issuer certificate!(发邮和签到都会提示以上错误)

![20180322132540](https://user-images.githubusercontent.com/12007315/37752842-e409542c-2dd4-11e8-9a1d-13d8cf5f1ebd.png)

(3)当我把pycurl降到7.19.0.2时,邮件能正常发送,没有了HTTP 599: SSL的错误提示,但签到功能还是不生效,而且会乱码!我已经尝试了几个pycurl版本!!来来去去都是这两个错误!
![20180322142305](https://user-images.githubusercontent.com/12007315/37754486-bad26ca8-2ddc-11e8-88d2-934cb1da50f2.png)

我收集了关于HTTP 599的错误问题,但我还未找到合适的解决办法!!
https://github.com/binux/pyspider/issues/372
https://github.com/binux/pyspider/issues/362
https://github.com/tornadoweb/tornado/issues/1724
https://www.cnblogs.com/shaosks/p/6856086.html

![20180322132524](https://user-images.githubusercontent.com/12007315/37752844-e7cca5a0-2dd4-11e8-8d02-869825842cbc.png)

![20180322134454](https://user-images.githubusercontent.com/12007315/37753314-4f089510-2dd7-11e8-9174-853af8f792f6.png)

@binux 
@eromoe

**Comment by binux** [comment]
apt-get install ca-certificates

**Comment by oe77** [comment]
@binux 马上测试

**Comment by oe77** [comment]
@binux 我的是window,还有我用smtp邮箱使用签到框架是无有任何问题的!!用mailgun邮箱才会出现上面现象!!证书我应该是有安装的

**Comment by oe77** [comment]
https://github.com/binux/pyspider/issues/362
我非常肯定他的问题跟我的是一样的,我跟他都是一样的系统!!一样的错误!!只是,他在pyspider出错,我在qiandao出错!


add curl's CA to system32 not work. I would add the verify_https = False on windows.
This is a curl bug, work fine on curl 7.46.0 (x86_64-w64-mingw32) but curl 7.37.0 (Windows)
这句话看上去,他好像解决了!!作者,,你知道他是怎么解决的吗??

**Comment by binux** [comment]
他说了「curl 7.46.0 (x86_64-w64-mingw32)」

**Comment by oe77** [comment]
@binux 谢谢！

**Comment by wakizasi** [comment]
额，我也遇到了这个问题，请问你有解决办法么？

**Comment by unicorn-yh** [comment]
错误原因：这个错误会发生在请求 https 开头的网址，SSL 验证错误，证书有误。
解决方法：使用self.crawl(url, callback=self.index_page, validate_cert=False)
